spring:
  application:
    name: gateway-service
  redis:
    host: 192.168.92.1
    port: 6379
    database: 0
#    password:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.92.1:9011
        username: nacos
        password: nacos
    gateway:
#      default-filters:
#        - name: Hystrix
#          args:
#            name: fallback
#            fallbackUri: forward:/global-error
      discovery:
        locator:
          # 禁用通过服务发现来自动地将请求路由到不同的服务实例
          enabled: false
      globalcors:
        # CorsConfiguration类
        cors-configurations:
#          '[/order]' :
          '[/**]' :
            allowed-origins:
              - "http://localhost:10000"
              - "*"
            # 设置哪些请求header可以进行跨域
            expose-header: "*"
#            exposedHeaders:
            allowCredentials: true
            allowed-methods: "*"
#            allowedMethods:
            allowed-headers: "*"
#            allowedHeaders:
            # 浏览器缓存时间
            max-age: 100
#            maxAge: 100
  sleuth:
    sampler:
      probability: 1
# zipkin集成

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enable: false

server:
  port: 30004


hystrix:
  # 全局配置
  default:
  #通用配置
  command:
    # 有的属性是默认值,写不写都行
  fallbackName:
    fallback:
      enabled: true
    circuitBreaker:
      enabled: true
      errorThresholdPercentage: 50
      requestVolumeThreshold: 5
      sleepWindowInMilliseconds: 10000
    execution:
      timeout:
        enabled: true
      isolation:
        thread:
          interruptOnTimeout: true
          interruptOnFutureCancel: true
          timeoutInMilliseconds: 2000 # 超时判定
